### ISSUE TITLE
Windows still mentioned as unsupported in README with broken link

### ISSUE THREAD

**Issue by Axolord** [bash/terminal-colorsaurus#27]
In September you deleted the windows.md file in the docs directory, since it was "no longer relevant", but the readme still states "windows is unfortunately unsupported" and links to that md file.

from your commits I gather, that windows terminal will be supported in the next release, right? So that should then probably also be mentioned in the readme. 

If that is the case, this lib would really be the one size fits all solution for this long standing problem, but already I am massively thankful that I can use bat again with the next release!

**Comment by bash** [comment]
You're absolutely right, I forgot to update the readme :)

Windows will be supported in the upcoming release—It depends on a change in Windows Terminal though which last I checked hasn't made it into stable yet :/

**Comment by Axolord** [comment]
Thanks for the clarification!
